import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react';
import { faker } from '@faker-js/faker';
import { albumsApi } from './albumsApi';


const photosApi = createApi({
    reducerPath: 'photos',
    //Wrapper around fetch
    //Function to handle request from a specific URL
    baseQuery: fetchBaseQuery({
        baseUrl: 'http://localhost:3005'
    }),

    //photo endpoints
    endpoints(builder) {
        return {
            fetchPhotos: builder.query({
                //define the shape of the response
                //https://localhost:3005/photos?albumId=1
                query: (album) => {
                    //return an object that matches the id in params
                    return {
                        url: '/photos',
                        //QUERY PARAMS FOR THE URL
                        params: {
                            albumId: album.id
                        },
                        method: 'GET',
                    }
                }
            }),
            addPhoto: builder.mutation({
                //define the shape of the request
                query: (album) => {
                    return {
                        method: 'POST',
                        url: '/photos',
                        //This will be sent
                        body: {
                            albumId: album.id,
                            url: faker.image.abstract(150, 150, true)
                        }
                    }
                }
            }),
            //define the shape of the request
            removePhoto: builder.mutation({
                query: (photo) => {
                    return {
                        method: 'DELETE',
                        url: `/photos/${photo.id}`,
                    };
                },
            }),
        };
    },
});

//Hooks generated by RTK to use in other components
export const {
    useFetchPhotosQuery,
    useAddPhotoMutation, 
    useRemovePhotoMutation,
} = photosApi;

export { photosApi }